trigger:
  batch: true
  branches:
    include:
    - 'master'
  paths:
    include:
    - Extensions/FluidTest.AzureSearch/*

pool:
  vmImage: 'windows-latest'

extends:
  template: /pipeline-templates/master.yml
  parameters:
      major : 1
      minor: 0
      patch: 0
      revision: 3
      projectPath: 'Extensions/FluidTest.AzureSearch/FluidTest.AzureSearch.csproj'