trigger:
  batch: true
  branches:
    include:
    - 'master'
  paths:
    include:
    - Engine/*

pool:
  vmImage: 'windows-latest'

extends:
  template: /pipeline-templates/master.yml
  parameters:
      major : 3
      minor: 0
      patch: 4
      revision: 0
      projectPath: 'Engine/Marktek.Fluent.Testing.Engine.csproj'
