trigger:
  batch: true
  branches:
    include:
    - '*'
  paths:
    include:
    - Extensions/FluidTest.AzureServiceBus/*

pool:
  vmImage: 'windows-latest'

extends:
  template: /pipeline-templates/master.yml
  parameters:
      major : 0
      minor: 0
      patch: 0
      revision: 1
      projectPath: 'Extensions/FluidTest.AzureServiceBus/FluidTest.AzureServiceBus.csproj'