trigger:
  batch: true
  branches:
    include:
    - 'master'
  paths:
    include:
    - Extensions/FluidTest.PowerPlatform/*

pool:
  vmImage: 'windows-latest'

extends:
  template: /pipeline-templates/master.yml
  parameters:
      major : 0
      minor: 0
      patch: 0
      revision: 2
      projectPath: 'Extensions/FluidTest.PowerPlatform/FluidTest.PowerPlatform.csproj'
