trigger:
  batch: true
  branches:
    include:
    - 'master'
  paths:
    include:
    - Extensions/FluidTest.AzureStorage/*

pool:
  vmImage: 'windows-latest'

extends:
  template: /pipeline-templates/master.yml
  parameters:
      major : 1
      minor: 0
      patch: 1
      revision: 0
      projectPath: 'Extensions/FluidTest.AzureStorage/FluidTest.AzureStorage.csproj'